version: '3.4'

services:
  app:
    build:
      args:
        RUN_PRECOMPILATION: 'false'
    volumes:
      - ".:/usr/src/app"
      - "tmp:/usr/src/app/tmp"
      - "storage:/usr/src/app/storage"
      - "node_modules:/usr/src/app/node_modules"
    ports:
      - "8080:3000"

volumes:
  tmp:
  storage:
  node_modules:
