mysql: &mysql
  adapter: mysql2
  encoding: utf8
  host: db
  port: 3306
  username: <%= p ENV; ENV.fetch('DB_USER') %>
  password: <%= p ENV; ENV.fetch('DB_PASS') %>

development:
  <<: *mysql
  database: development

staging:
  <<: *mysql
  database: govwifi_admin_staging

production:
  <<: *mysql
  database: govwifi_admin_production

test:
  <<: *mysql
  database: govwifi_admin_test
