default: &default
  end_user_docs_link: 'https://www.wifi.service.gov.uk/connect-to-govwifi/'
  end_user_troubleshooting_link: 'https://www.wifi.service.gov.uk/connect-to-govwifi/get-help-connecting/'
  organisation_docs_link: 'https://docs.wifi.service.gov.uk'
  support_link: 'https://www.wifi.service.gov.uk/connect-to-govwifi/get-help-connecting/'
  connect_to_govwifi_link: 'https://www.wifi.service.gov.uk/connect-to-govwifi/'
  cookies_docs_link: 'https://www.wifi.service.gov.uk/cookies'
  product_page_link: 'https://wifi.service.gov.uk'
  default_page_title: 'GovWifi admin'
  default_meta_description: 'GovWifi - Administration Platform'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
